routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('index');
})->name('index');

Route::view('/privacy', 'page.privacy')->name('privacy');
Route::view('/tos', 'page.tos')->name('tos');

Route::get('/contact', 'HomeController@contact')->name('contact');

Auth::routes();

Route::get('/checkout', 'TicketController@checkout');


Route::group(['prefix' => 'trip'], function () {
    Route::get('/search', 'TripController@search')->name('trip.search');

    Route::group(['prefix' => 'book'], function () {
        Route::get('/information', 'TicketController@book');
        Route::post('/checkout', 'TicketController@checkout');
        Route::get('/success/{id}', 'TicketController@success');
    });
});

Route::group(['prefix' => 'ticket'], function () {
    Route::get('/information/{ticket}/{checkout_id}', 'TicketController@information')->name('ticket.information');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin|tenant']], function () {
    Route::get('/', 'AdminController@index')->name('admin.index');

    Route::group(['prefix' => 'invoces'], function () {
        Route::get('/', 'InvoiceController@index')->name('admin.invoice.index');
        Route::get('/{id}', 'InvoiceController@view')->name('admin.invoice.view');

        Route::post('/issue/refund', 'InvoiceController@issueRefund')->name('admin.invoice.refund');
    });

    Route::group(['prefix' => 'tickets'], function () {
        Route::get('/', 'TicketController@index')->name('admin.ticket.index');

        Route::get('/create', 'TicketController@create')->name('admin.ticket.create');

        Route::get('/{id}', 'TicketController@view')->name('admin.ticket.view');
    });

    Route::group(['prefix' => 'users', 'middleware' => ['role:admin']], function () {
        Route::get('/', 'UserController@index')->name('admin.users.index');

        Route::get('/create', 'UserController@create')->name('admin.users.create');
        Route::post('/', 'UserController@store')->name('admin.users.store');

        Route::get('/{id}/edit', 'UserController@edit')->name('admin.users.edit');
        Route::post('/{id}', 'UserController@update')->name('admin.users.update');

        Route::delete('/{id}', 'UserController@destroy')->name('admin.users.destroy');
    });

    Route::group(['prefix' => 'buses'], function () {
        Route::get('/', 'BusController@index')->name('admin.buses.index');

        Route::get('/create', 'BusController@create')->name('admin.buses.create');
        Route::post('/', 'BusController@store')->name('admin.buses.store');

        Route::get('/{id}/edit', 'BusController@edit')->name('admin.buses.edit');
        Route::post('/{id}', 'BusController@update')->name('admin.buses.update');

        Route::delete('/{id}', 'BusController@destroy')->name('admin.buses.destroy');
    });

    Route::group(['prefix' => 'seats'], function () {
        Route::get('/', 'SeatLayoutController@index')->name('admin.seats.index');
        Route::get('/create', 'SeatLayoutController@create')->name('admin.seats.create');

        Route::get('/{id}/edit', 'SeatLayoutController@edit')->name('admin.seats.edit');

        Route::delete('/{id}', 'SeatLayoutController@destroy')->name('admin.seats.destroy');
    });

    Route::group(['prefix' => 'liners', 'middleware' => ['role:admin']], function () {
        Route::get('/', 'LinerController@index')->name('admin.liners.index');

        Route::get('/create', 'LinerController@create')->name('admin.liners.create');
        Route::post('/', 'LinerController@store')->name('admin.liners.store');

        Route::get('/{id}/edit', 'LinerController@edit')->name('admin.liners.edit');
        Route::post('/{id}', 'LinerController@update')->name('admin.liners.update');

        Route::delete('/{id}', 'LinerController@destroy')->name('admin.liners.destroy');
    });

    Route::group(['prefix' => 'trips'], function () {

        Route::post('/', 'TripController@store')->name('admin.trips.store');
        Route::get('/create', 'TripController@create')->name('admin.trips.create');

        Route::get('/{id}/edit', 'TripController@edit')->name('admin.trips.edit');
        Route::post('/{id}', 'TripController@update')->name('admin.trips.update');

        Route::delete('/{id}', 'TripController@destroy')->name('admin.trips.destroy');

        Route::get('/{type?}', 'TripController@index')->name('admin.trips.index');
    });

    Route::group(['prefix' => 'locations', 'middleware' => ['role:admin']], function () {
        Route::get('/', 'LocationController@index')->name('admin.locations.index');

        Route::namespace('Location')->group(function(){
            Route::group(['prefix' => 'province'], function () {

                Route::get('/create', 'ProvinceController@create')->name('admin.province.create');
                Route::post('/', 'ProvinceController@store')->name('admin.province.store');

                Route::get('/{id}/edit', 'ProvinceController@edit')->name('admin.province.edit');
                Route::post('/{id}', 'ProvinceController@update')->name('admin.province.update');

                Route::delete('/{id}', 'ProvinceController@destroy')->name('admin.province.destroy');

                Route::get('/{id}', 'ProvinceController@view')->name('admin.province.view');


                Route::get('/{provinceID}/city/create', 'CityController@create')->name('admin.city.create');
                Route::post('/{provinceID}/city/create', 'CityController@store')->name('admin.city.store');

                Route::get('/{provinceID}/city/{cityID}/edit', 'CityController@edit')->name('admin.city.edit');
                Route::post('/{provinceID}/city/{cityID}', 'CityController@update')->name('admin.city.update');
                Route::delete('/{provinceID}/city/{cityID}', 'CityController@destroy')->name('admin.city.destroy');



            });

            Route::group(['prefix' => 'city'], function () {
                Route::get('/{id}', 'CityController@view')->name('admin.city.view');

                Route::get('/{id}/terminal/create', 'TerminalController@create')->name('admin.terminal.create');

                Route::post('/{id}/terminal/create', 'TerminalController@store')->name('admin.terminal.store');

                Route::get('/{cityID}/terminal/{terminalID}/edit', 'TerminalController@edit')->name('admin.terminal.edit');

                Route::post('/{cityID}/terminal/{terminalID}', 'TerminalController@update')->name('admin.terminal.update');

                Route::delete('/{cityID}/terminal/{terminalID}', 'TerminalController@destroy')->name('admin.terminal.destroy');

            });
        });

    });

    Route::group(['prefix' => 'api'], function () {
        Route::group(['prefix' => 'seats'], function () {
            Route::post('/store', 'SeatLayoutController@store');
            Route::post('/get', 'SeatLayoutController@get');

            Route::post('/{id}', 'SeatLayoutController@update');
        });

        Route::group(['prefix' => 'liners'], function () {
            Route::post('/get', 'LinerController@get');
        });

        Route::group(['prefix' => 'buses'], function () {
            Route::post('/get', 'BusController@get');
        });

        Route::group(['prefix' => 'locations'], function () {
            Route::post('/terminals', 'LocationController@terminals');
            Route::post('/provinces', 'LocationController@provinces');
        });

        Route::group(['prefix' => 'trips'], function () {
            Route::post('/', 'TicketController@store');
            Route::post('/get', 'TripController@getById');
            Route::post('/search/{type?}', 'TripController@searchApi');
        });
    });
});

Route::group(['prefix' => 'api'], function () {
    Route::group(['prefix' => 'trips'], function () {
        Route::post('/search', 'TripController@searchApi');
    });
    Route::group(['prefix' => 'locations'], function () {
        Route::post('/provinces', 'LocationController@provinces');
    });
    Route::group(['prefix' => 'liners'], function () {
        Route::post('/', 'LinerController@getById');
    });
    Route::group(['prefix' => 'tickets'], function () {
        Route::post('/', 'TicketController@reservations');
        Route::post('/session', 'TicketController@reserveSession');
    });
});

app/Liner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Liner extends Model{

    protected $appends = ['logo_url'];

    public function buses(){
        return $this->hasMany(Bus::class);
    }

    public function getLogoUrlAttribute(){
        return asset('images/liners/'.$this->logo);
    }

    public function trips(){
        return $this->hasMany(Trip::class);
    }

}

app/Http/Controllers/LinerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Liner;

class LinerController extends Controller{

    public function index(){
        $liners = Liner::withCount('buses')->paginate(10);

        return view('admin.liners.index', compact('liners'));
    }

    public function create(){
        return view('admin.liners.create');
    }

    public function store(Request $request){
        $request->validate([
            'name' => 'required',
            'mobile_number' => 'required|numeric|min:11',
            'logo' => 'required|image',
            'address' => 'required',
        ]);

        $file = $request->logo;

        if(!$file->isValid()){
            flash('Invalid Uploaded Logo')->error();
            return redirect()->route('admin.liners.create');
        }

        $fileInfo = pathinfo($file->getClientOriginalName());

        $fileName = md5($fileInfo['filename']).'.'.$fileInfo['extension'];

        $file->storeAs('liners', $fileName, 'images');

        $liner = new Liner;
        $liner->name = $request->name;
        $liner->mobile_number = $request->mobile_number;
        $liner->address = $request->address;
        $liner->logo = $fileName;
        $liner->save();

        flash('Successfully Added.')->success();

        return redirect()->route('admin.liners.create');

    }

    public function edit($id){
        $liner = Liner::where('id', $id)->firstOrFail();

        return view('admin.liners.edit', compact('liner'));
    }

    public function update(Request $request){

        $request->validate([
            'name' => 'required',
            'mobile_number' => 'required|numeric|min:11',
            'logo' => 'image',
            'address' => 'required',
        ]);

        $liner = Liner::where('id', $request->id)->firstOrFail();

        if($request->logo){
            $file = $request->logo;

            if(!$file->isValid()){
                flash('Invalid Uploaded Logo')->error();
                return redirect()->route('admin.liners.create');
            }

            $fileInfo = pathinfo($file->getClientOriginalName());

            $fileName = md5($fileInfo['filename']).'.'.$fileInfo['extension'];

            $file->storeAs('liners', $fileName, 'images');

            $liner->logo = $fileName;
        }

        $liner->name = $request->name;
        $liner->mobile_number = $request->mobile_number;
        $liner->address = $request->address;
        $liner->save();

        flash('Successfully Updated.')->success();

        return redirect()->route('admin.liners.edit', $liner->id);

    }

    public function destroy($id){
        $liner = Liner::where('id', $id)->firstOrFail();
        $liner->delete();

        flash('Successfully Deleted.')->success();
        return redirect()->route('admin.liners.index');

    }

    //API

    public function get(){
        $liners = Liner::all();

        return response()->json([
            'status' => true,
            'results' => $liners
        ]);
    }

    public function getById(Request $request){

        $liner = Liner::where('id', $request->id)->first();

        if(!$liner){
            return response()->json([
                'status' => false
            ]);
        }

        return response()->json([
            'status' => true,
            'result' => $liner
        ]);

    }

}

resources/views/admin/liners/create.blade.php
@extends('admin.layouts.admin')

@section('content')
    <form class="card" method="POST" action="{{ route('admin.liners.store') }}" enctype="multipart/form-data">
        <div class="card-header">
            <h3 class="card-title">Add new Liner</h3>
        </div>
        @include('flash::message')
        <div class="card-body">
            <div class="row">
                <div class="form-group col-md-6">
                    <label>Name</label>
                    <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}">
                    @if ($errors->has('name'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group col-md-3">
                    <label>Mobile Number/Phone Number</label>
                    <input type="text" class="form-control{{ $errors->has('mobile_number') ? ' is-invalid' : '' }}" name="mobile_number" value="{{ old('mobile_number') }}">
                    @if ($errors->has('mobile_number'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('mobile_number') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group col-md-3">
                    <label>Logo</label>
                    <input type="file" class="form-control-file{{ $errors->has('logo') ? ' is-invalid' : '' }}" name="logo">
                    @if ($errors->has('logo'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('logo') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group col-md-12">
                    <label>Address</label>
                    <textarea class="form-control{{ $errors->has('address') ? ' is-invalid' : '' }}" name="address">{{ old('address') }} </textarea>
                    @if ($errors->has('address'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('address') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
        </div>
        <div class="card-footer">
            @csrf
            <button class="btn btn-primary" type="submit">Submit</button>
        </div>
    </form>
@endsection

resources/views/admin/liners/edit.blade.php
@extends('admin.layouts.admin')

@section('content')
    <form class="card" method="POST" action="{{ route('admin.liners.update', $liner->id) }}" enctype="multipart/form-data">
        <div class="card-header">
            <h3 class="card-title">Edit '<b>{{ $liner->name }}</b>' Liner</h3>
        </div>
        @include('flash::message')
        <div class="card-body">
            <div class="row">
                <div class="form-group col-md-6">
                    <label>Name</label>
                    <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ $liner->name }}">
                    @if ($errors->has('name'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group col-md-5">
                    <label>Mobile Number</label>
                    <input type="text" class="form-control{{ $errors->has('mobile_number') ? ' is-invalid' : '' }}" name="mobile_number" value="{{ $liner->mobile_number }}">
                    @if ($errors->has('mobile_number'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('mobile_number') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group col-md-5">
                    <label>Address</label>
                    <textarea class="form-control{{ $errors->has('address') ? ' is-invalid' : '' }}" name="address" rows="2">{{ $liner->address }} </textarea>
                    @if ($errors->has('address'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('address') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group col-md-3">
                    <label>Logo</label>
                    <input type="file" class="form-control-file{{ $errors->has('logo') ? ' is-invalid' : '' }}" name="logo">
                    @if ($errors->has('logo'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('logo') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group col-md-3">
                    Current Logo: <br>
                    <img src="{{ $liner->logo_url }}" width="100px" alt=""><br>
                </div>
            </div>
        </div>
        <div class="card-footer">
            @csrf
            <button class="btn btn-primary" type="submit">Submit</button>
        </div>
    </form>
@endsection

resources/views/admin/liners/index.blade.php
@extends('admin.layouts.admin')

@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">List of Liners</h3>
        </div>
        @include('flash::message')
        <table class="table table-striped mb-0">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Total Bus</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($liners as $liner)
                    <tr>
                        <th scope="row">{{ $liner->id }}</th>
                        <td>{{ $liner->name }}</td>
                        <td>{{ $liner->buses_count }}</td>
                        <td>
                            <form action="{{ route('admin.liners.destroy', $liner->id) }}" method="POST">
                                <a href="{{ route('admin.liners.edit', $liner->id) }}" class="btn btn-secondary btn-sm">Update</a>
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    {{ $liners->render() }}
@endsection