routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('index');
})->name('index');

Route::view('/privacy', 'page.privacy')->name('privacy');
Route::view('/tos', 'page.tos')->name('tos');

Route::get('/contact', 'HomeController@contact')->name('contact');

Auth::routes();

Route::get('/checkout', 'TicketController@checkout');


Route::group(['prefix' => 'trip'], function () {
    Route::get('/search', 'TripController@search')->name('trip.search');

    Route::group(['prefix' => 'book'], function () {
        Route::get('/information', 'TicketController@book');
        Route::post('/checkout', 'TicketController@checkout');
        Route::get('/success/{id}', 'TicketController@success');
    });
});

Route::group(['prefix' => 'ticket'], function () {
    Route::get('/information/{ticket}/{checkout_id}', 'TicketController@information')->name('ticket.information');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin|tenant']], function () {
    Route::get('/', 'AdminController@index')->name('admin.index');

    Route::group(['prefix' => 'invoces'], function () {
        Route::get('/', 'InvoiceController@index')->name('admin.invoice.index');
        Route::get('/{id}', 'InvoiceController@view')->name('admin.invoice.view');

        Route::post('/issue/refund', 'InvoiceController@issueRefund')->name('admin.invoice.refund');
    });

    Route::group(['prefix' => 'tickets'], function () {
        Route::get('/', 'TicketController@index')->name('admin.ticket.index');

        Route::get('/create', 'TicketController@create')->name('admin.ticket.create');

        Route::get('/{id}', 'TicketController@view')->name('admin.ticket.view');
    });

    Route::group(['prefix' => 'users', 'middleware' => ['role:admin']], function () {
        Route::get('/', 'UserController@index')->name('admin.users.index');

        Route::get('/create', 'UserController@create')->name('admin.users.create');
        Route::post('/', 'UserController@store')->name('admin.users.store');

        Route::get('/{id}/edit', 'UserController@edit')->name('admin.users.edit');
        Route::post('/{id}', 'UserController@update')->name('admin.users.update');

        Route::delete('/{id}', 'UserController@destroy')->name('admin.users.destroy');
    });

    Route::group(['prefix' => 'buses'], function () {
        Route::get('/', 'BusController@index')->name('admin.buses.index');

        Route::get('/create', 'BusController@create')->name('admin.buses.create');
        Route::post('/', 'BusController@store')->name('admin.buses.store');

        Route::get('/{id}/edit', 'BusController@edit')->name('admin.buses.edit');
        Route::post('/{id}', 'BusController@update')->name('admin.buses.update');

        Route::delete('/{id}', 'BusController@destroy')->name('admin.buses.destroy');
    });

    Route::group(['prefix' => 'seats'], function () {
        Route::get('/', 'SeatLayoutController@index')->name('admin.seats.index');
        Route::get('/create', 'SeatLayoutController@create')->name('admin.seats.create');

        Route::get('/{id}/edit', 'SeatLayoutController@edit')->name('admin.seats.edit');

        Route::delete('/{id}', 'SeatLayoutController@destroy')->name('admin.seats.destroy');
    });

    Route::group(['prefix' => 'liners', 'middleware' => ['role:admin']], function () {
        Route::get('/', 'LinerController@index')->name('admin.liners.index');

        Route::get('/create', 'LinerController@create')->name('admin.liners.create');
        Route::post('/', 'LinerController@store')->name('admin.liners.store');

        Route::get('/{id}/edit', 'LinerController@edit')->name('admin.liners.edit');
        Route::post('/{id}', 'LinerController@update')->name('admin.liners.update');

        Route::delete('/{id}', 'LinerController@destroy')->name('admin.liners.destroy');
    });

    Route::group(['prefix' => 'trips'], function () {

        Route::post('/', 'TripController@store')->name('admin.trips.store');
        Route::get('/create', 'TripController@create')->name('admin.trips.create');

        Route::get('/{id}/edit', 'TripController@edit')->name('admin.trips.edit');
        Route::post('/{id}', 'TripController@update')->name('admin.trips.update');

        Route::delete('/{id}', 'TripController@destroy')->name('admin.trips.destroy');

        Route::get('/{type?}', 'TripController@index')->name('admin.trips.index');
    });

    Route::group(['prefix' => 'locations', 'middleware' => ['role:admin']], function () {
        Route::get('/', 'LocationController@index')->name('admin.locations.index');

        Route::namespace('Location')->group(function(){
            Route::group(['prefix' => 'province'], function () {

                Route::get('/create', 'ProvinceController@create')->name('admin.province.create');
                Route::post('/', 'ProvinceController@store')->name('admin.province.store');

                Route::get('/{id}/edit', 'ProvinceController@edit')->name('admin.province.edit');
                Route::post('/{id}', 'ProvinceController@update')->name('admin.province.update');

                Route::delete('/{id}', 'ProvinceController@destroy')->name('admin.province.destroy');

                Route::get('/{id}', 'ProvinceController@view')->name('admin.province.view');


                Route::get('/{provinceID}/city/create', 'CityController@create')->name('admin.city.create');
                Route::post('/{provinceID}/city/create', 'CityController@store')->name('admin.city.store');

                Route::get('/{provinceID}/city/{cityID}/edit', 'CityController@edit')->name('admin.city.edit');
                Route::post('/{provinceID}/city/{cityID}', 'CityController@update')->name('admin.city.update');
                Route::delete('/{provinceID}/city/{cityID}', 'CityController@destroy')->name('admin.city.destroy');



            });

            Route::group(['prefix' => 'city'], function () {
                Route::get('/{id}', 'CityController@view')->name('admin.city.view');

                Route::get('/{id}/terminal/create', 'TerminalController@create')->name('admin.terminal.create');

                Route::post('/{id}/terminal/create', 'TerminalController@store')->name('admin.terminal.store');

                Route::get('/{cityID}/terminal/{terminalID}/edit', 'TerminalController@edit')->name('admin.terminal.edit');

                Route::post('/{cityID}/terminal/{terminalID}', 'TerminalController@update')->name('admin.terminal.update');

                Route::delete('/{cityID}/terminal/{terminalID}', 'TerminalController@destroy')->name('admin.terminal.destroy');

            });
        });

    });

    Route::group(['prefix' => 'api'], function () {
        Route::group(['prefix' => 'seats'], function () {
            Route::post('/store', 'SeatLayoutController@store');
            Route::post('/get', 'SeatLayoutController@get');

            Route::post('/{id}', 'SeatLayoutController@update');
        });

        Route::group(['prefix' => 'liners'], function () {
            Route::post('/get', 'LinerController@get');
        });

        Route::group(['prefix' => 'buses'], function () {
            Route::post('/get', 'BusController@get');
        });

        Route::group(['prefix' => 'locations'], function () {
            Route::post('/terminals', 'LocationController@terminals');
            Route::post('/provinces', 'LocationController@provinces');
        });

        Route::group(['prefix' => 'trips'], function () {
            Route::post('/', 'TicketController@store');
            Route::post('/get', 'TripController@getById');
            Route::post('/search/{type?}', 'TripController@searchApi');
        });
    });
});

Route::group(['prefix' => 'api'], function () {
    Route::group(['prefix' => 'trips'], function () {
        Route::post('/search', 'TripController@searchApi');
    });
    Route::group(['prefix' => 'locations'], function () {
        Route::post('/provinces', 'LocationController@provinces');
    });
    Route::group(['prefix' => 'liners'], function () {
        Route::post('/', 'LinerController@getById');
    });
    Route::group(['prefix' => 'tickets'], function () {
        Route::post('/', 'TicketController@reservations');
        Route::post('/session', 'TicketController@reserveSession');
    });
});

app/Http/Controllers/Location/CityController.php
<?php

namespace App\Http\Controllers\Location;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Location\City;
use App\Location\Terminal;
use App\Location\Province;

class CityController extends Controller{

    public function view($id){

        $city = City::where('id', $id)->firstOrFail();

        return view('admin.location.city.view', compact('city'));

    }

    public function edit($provinceID, $cityID){
        $city = City::where('id', $cityID)->where('province_id', $provinceID)->firstOrFail();

        return view('admin.location.city.edit', compact('city'));
    }

    public function update($provinceID, $cityID, Request $request){
        $city = City::where('id', $cityID)->where('province_id', $provinceID)->firstOrFail();

        $request->validate([
            'name' => 'required'
        ]);

        $city->name = $request->name;
        $city->save();

        flash('Successfully Updated')->success();

        return redirect()->route('admin.province.view', $city->province_id);
    }

    public function create($id){
        $province = Province::where('id', $id)->firstOrFail();

        return view('admin.location.city.create', compact('province'));
    }

    public function store($id, Request $request){

        $province = Province::where('id', $id)->firstOrFail();

        $request->validate([
            'name' => 'required',
        ]);

        $city = City::create([
            'province_id' => $province->id,
            'name' => $request->name
        ]);

        flash('Successfully Added')->success();

        return redirect()->route('admin.province.view', $province->id);
    }

    public function destroy($provinceID, $cityID){

        $city = City::where('id', $cityID)->where('province_id', $provinceID)->firstOrFail();
        $city->delete();

        flash('Successfully Deleted')->success();
        return redirect()->route('admin.province.view', $provinceID);

    }
}

app/Http/Controllers/Location/ProvinceController.php
<?php

namespace App\Http\Controllers\Location;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Location\Province;

class ProvinceController extends Controller{

    public function view($id){
        $province = Province::where('id', $id)->with(['cities' => function($q){
            $q->withCount('terminals');
        }])->firstOrFail();

        return view('admin.location.province.view', compact('province'));
    }

    public function create(){
        return view('admin.location.province.create');
    }

    public function store(Request $request){
        $request->validate([
            'name' => 'required'
        ]);

        $province = Province::create([
            'name' => $request->name
        ]);

        flash('Successfully added')->success();
        return redirect()->route('admin.locations.index');

    }

    public function edit($id){
        $province = Province::where('id', $id)->firstOrFail();


        return view('admin.location.province.edit', compact('province'));

    }

    public function update($id, Request $request){
        $province = Province::where('id', $id)->firstOrFail();

        $request->validate([
            'name' => 'required'
        ]);

        $province->name = $request->name;
        $province->save();

        flash('Successfully updated')->success();

        return redirect()->route('admin.locations.index');
    }

    public function destroy($id){
        $province = Province::where('id', $id)->firstOrFail();
        $province->delete();

        flash('Successfully deleted')->success();
        return redirect()->route('admin.locations.index');

    }
}

app/Http/Controllers/Location/TerminalController.php
<?php

namespace App\Http\Controllers\Location;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Location\Terminal;
use App\Location\City;

class TerminalController extends Controller{

    public function create($id){
        $city = City::where('id', $id)->firstOrFail();

        return view('admin.location.terminal.create', compact('city'));
    }

    public function store($id, Request $request){

        $city = City::where('id', $id)->firstOrFail();

        $request->validate([
            'name' => 'required',
        ]);

        $terminal = Terminal::create([
            'city_id' => $city->id,
            'province_id' => $city->province_id,
            'name' => $request->name
        ]);

        flash('Successfully Added')->success();

        return redirect()->route('admin.city.view', $city->id);

    }

    public function edit($cityID, $terminalID){
        $terminal = Terminal::where('id', $terminalID)->where('city_id', $cityID)->firstOrFail();

        return view('admin.location.terminal.edit', compact('terminal'));
    }

    public function update($cityID, $terminalID, Request $request){

        $terminal = Terminal::where('id', $terminalID)->where('city_id', $cityID)->firstOrFail();

        $request->validate([
            'name' => 'required'
        ]);

        $terminal->name = $request->name;
        $terminal->save();

        flash('Successfully Updated')->success();

        return redirect()->route('admin.city.view', $terminal->city_id);

    }

    public function destroy($cityID, $terminalID){
        $terminal = Terminal::where('id', $terminalID)->where('city_id', $cityID)->firstOrFail();
        $terminal->delete();

        flash('Successfully Deleted')->success();
        return redirect()->route('admin.city.view', $cityID);

    }

}

app/Http/Controllers/LocationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Location\Terminal;
use App\Location\City;
use App\Location\Province;

class LocationController extends Controller{

    public function index(){
        $provinces = Province::withCount(['terminals', 'cities'])->paginate(10);

        return view('admin.location.index', compact('provinces'));
    }

    public function view($id){
        $province = Province::where('id', $id)->with(['cities' => function($q){
            $q->withCount('terminals');
        }])->firstOrFail();

        return view('admin.location.province.view', compact('province'));
    }

    public function terminals(Request $request){
        $dPoints = array();
        $dLocations = array_pluck((array)$request->droppingPoints, 'location');
            foreach($dLocations as $locations){
                if(is_array($locations)){
                    $location = array_first($locations);
                    if(is_array($location)){
                        $dPoints[] = $location['id'];
                    }
                }
            }
            // dd($request->boardingPoint);
        // $dPoints = array_pluck((array)$dLocations);
        $bPoints = is_array($request->boardingPoint) ? array_first($request->boardingPoint)['id'] : null;

        array_push($dPoints, $bPoints);

        $clean = array_filter($dPoints);

        $terminals = Terminal::where('name', 'LIKE', '%'.$request->q.'%')->whereNotIn('id', $clean)->select('id', 'name')->get();

        return response()->json([
            'status' => true,
            'results' => $terminals,
        ]);
    }

    public function provinces(){
        $provinces = Province::with('cities')->get();

        return response()->json([
            'status' => true,
            'results' => $provinces
        ]);
    }

}

resources/views/admin/location/province/create.blade.php
@extends('admin.layouts.admin')

@section('content')
    <form class="card" method="POST" action="{{ route('admin.province.store') }}" enctype="multipart/form-data">
        <div class="card-header">
            <h3 class="card-title">Add new Province</h3>
        </div>
        @include('flash::message')
        <div class="card-body">
            <div class="row">
                <div class="form-group col-md-12">
                    <label>Name</label>
                    <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}">
                    @if ($errors->has('name'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
        </div>
        <div class="card-footer">
            @csrf
            <button class="btn btn-primary" type="submit">Submit</button>
        </div>
    </form>
@endsection

resources/views/admin/location/province/edit.blade.php
@extends('admin.layouts.admin')

@section('content')
    <form class="card" method="POST" action="{{ route('admin.province.update', $province->id) }}" enctype="multipart/form-data">
        <div class="card-header">
            <h3 class="card-title">Edit Province {{ $province->name }}</h3>
        </div>
        @include('flash::message')
        <div class="card-body">
            <div class="row">
                <div class="form-group col-md-12">
                    <label>Name</label>
                    <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ $province->name }}">
                    @if ($errors->has('name'))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>
        </div>
        <div class="card-footer">
            @csrf
            <button class="btn btn-primary" type="submit">Update</button>
        </div>
    </form>
@endsection

resources/views/admin/location/province/view.blade.php
@extends('admin.layouts.admin')

@section('content')
<div class="card">
    <div class="card-header">
        <h3 class="card-title">
            Province of {{ $province->name }} Information
        </h3>
    </div>
    @include('flash::message')
    <div class="card-body">
        <div class="row">
            <div class="col-md-8 offset-md-2">
            <a href="{{ route('admin.city.create', $province->id) }}" class="btn btn-primary btn-sm float-right">Add new City</a>
                <h4>List of Cities</h4>
                <table class="table mb-0">
                    <thead>
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Total Terminal</th>
                        <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($province->cities as $city)
                        <tr>
                            <th scope="row">{{ $city->id }}</th>
                            <td>{{ $city->name }}</td>
                            <td>{{ $city->terminals_count }}</td>
                            <td>
                                <form action="{{ route('admin.city.destroy', [
                                        'provinceID' => $province->id,
                                        'cityID' => $city->id
                                    ]) }}" method="POST">
                                    <a href="{{ route('admin.city.view', $city->id) }}" class="btn btn-secondary btn-sm">View</a>
                                    <a href="{{ route('admin.city.edit', [
                                        'provinceID' => $province->id,
                                        'cityID' => $city->id
                                    ]) }}" class="btn btn-secondary btn-sm">Update</a>
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete?')">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>
@endsection