routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('index');
})->name('index');

Route::view('/privacy', 'page.privacy')->name('privacy');
Route::view('/tos', 'page.tos')->name('tos');

Route::get('/contact', 'HomeController@contact')->name('contact');

Auth::routes();

Route::get('/checkout', 'TicketController@checkout');


Route::group(['prefix' => 'trip'], function () {
    Route::get('/search', 'TripController@search')->name('trip.search');

    Route::group(['prefix' => 'book'], function () {
        Route::get('/information', 'TicketController@book');
        Route::post('/checkout', 'TicketController@checkout');
        Route::get('/success/{id}', 'TicketController@success');
    });
});

Route::group(['prefix' => 'ticket'], function () {
    Route::get('/information/{ticket}/{checkout_id}', 'TicketController@information')->name('ticket.information');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'role:admin|tenant']], function () {
    Route::get('/', 'AdminController@index')->name('admin.index');

    Route::group(['prefix' => 'invoces'], function () {
        Route::get('/', 'InvoiceController@index')->name('admin.invoice.index');
        Route::get('/{id}', 'InvoiceController@view')->name('admin.invoice.view');

        Route::post('/issue/refund', 'InvoiceController@issueRefund')->name('admin.invoice.refund');
    });

    Route::group(['prefix' => 'tickets'], function () {
        Route::get('/', 'TicketController@index')->name('admin.ticket.index');

        Route::get('/create', 'TicketController@create')->name('admin.ticket.create');

        Route::get('/{id}', 'TicketController@view')->name('admin.ticket.view');
    });

    Route::group(['prefix' => 'users', 'middleware' => ['role:admin']], function () {
        Route::get('/', 'UserController@index')->name('admin.users.index');

        Route::get('/create', 'UserController@create')->name('admin.users.create');
        Route::post('/', 'UserController@store')->name('admin.users.store');

        Route::get('/{id}/edit', 'UserController@edit')->name('admin.users.edit');
        Route::post('/{id}', 'UserController@update')->name('admin.users.update');

        Route::delete('/{id}', 'UserController@destroy')->name('admin.users.destroy');
    });

    Route::group(['prefix' => 'buses'], function () {
        Route::get('/', 'BusController@index')->name('admin.buses.index');

        Route::get('/create', 'BusController@create')->name('admin.buses.create');
        Route::post('/', 'BusController@store')->name('admin.buses.store');

        Route::get('/{id}/edit', 'BusController@edit')->name('admin.buses.edit');
        Route::post('/{id}', 'BusController@update')->name('admin.buses.update');

        Route::delete('/{id}', 'BusController@destroy')->name('admin.buses.destroy');
    });

    Route::group(['prefix' => 'seats'], function () {
        Route::get('/', 'SeatLayoutController@index')->name('admin.seats.index');
        Route::get('/create', 'SeatLayoutController@create')->name('admin.seats.create');

        Route::get('/{id}/edit', 'SeatLayoutController@edit')->name('admin.seats.edit');

        Route::delete('/{id}', 'SeatLayoutController@destroy')->name('admin.seats.destroy');
    });

    Route::group(['prefix' => 'liners', 'middleware' => ['role:admin']], function () {
        Route::get('/', 'LinerController@index')->name('admin.liners.index');

        Route::get('/create', 'LinerController@create')->name('admin.liners.create');
        Route::post('/', 'LinerController@store')->name('admin.liners.store');

        Route::get('/{id}/edit', 'LinerController@edit')->name('admin.liners.edit');
        Route::post('/{id}', 'LinerController@update')->name('admin.liners.update');

        Route::delete('/{id}', 'LinerController@destroy')->name('admin.liners.destroy');
    });

    Route::group(['prefix' => 'trips'], function () {

        Route::post('/', 'TripController@store')->name('admin.trips.store');
        Route::get('/create', 'TripController@create')->name('admin.trips.create');

        Route::get('/{id}/edit', 'TripController@edit')->name('admin.trips.edit');
        Route::post('/{id}', 'TripController@update')->name('admin.trips.update');

        Route::delete('/{id}', 'TripController@destroy')->name('admin.trips.destroy');

        Route::get('/{type?}', 'TripController@index')->name('admin.trips.index');
    });

    Route::group(['prefix' => 'locations', 'middleware' => ['role:admin']], function () {
        Route::get('/', 'LocationController@index')->name('admin.locations.index');

        Route::namespace('Location')->group(function(){
            Route::group(['prefix' => 'province'], function () {

                Route::get('/create', 'ProvinceController@create')->name('admin.province.create');
                Route::post('/', 'ProvinceController@store')->name('admin.province.store');

                Route::get('/{id}/edit', 'ProvinceController@edit')->name('admin.province.edit');
                Route::post('/{id}', 'ProvinceController@update')->name('admin.province.update');

                Route::delete('/{id}', 'ProvinceController@destroy')->name('admin.province.destroy');

                Route::get('/{id}', 'ProvinceController@view')->name('admin.province.view');


                Route::get('/{provinceID}/city/create', 'CityController@create')->name('admin.city.create');
                Route::post('/{provinceID}/city/create', 'CityController@store')->name('admin.city.store');

                Route::get('/{provinceID}/city/{cityID}/edit', 'CityController@edit')->name('admin.city.edit');
                Route::post('/{provinceID}/city/{cityID}', 'CityController@update')->name('admin.city.update');
                Route::delete('/{provinceID}/city/{cityID}', 'CityController@destroy')->name('admin.city.destroy');



            });

            Route::group(['prefix' => 'city'], function () {
                Route::get('/{id}', 'CityController@view')->name('admin.city.view');

                Route::get('/{id}/terminal/create', 'TerminalController@create')->name('admin.terminal.create');

                Route::post('/{id}/terminal/create', 'TerminalController@store')->name('admin.terminal.store');

                Route::get('/{cityID}/terminal/{terminalID}/edit', 'TerminalController@edit')->name('admin.terminal.edit');

                Route::post('/{cityID}/terminal/{terminalID}', 'TerminalController@update')->name('admin.terminal.update');

                Route::delete('/{cityID}/terminal/{terminalID}', 'TerminalController@destroy')->name('admin.terminal.destroy');

            });
        });

    });

    Route::group(['prefix' => 'api'], function () {
        Route::group(['prefix' => 'seats'], function () {
            Route::post('/store', 'SeatLayoutController@store');
            Route::post('/get', 'SeatLayoutController@get');

            Route::post('/{id}', 'SeatLayoutController@update');
        });

        Route::group(['prefix' => 'liners'], function () {
            Route::post('/get', 'LinerController@get');
        });

        Route::group(['prefix' => 'buses'], function () {
            Route::post('/get', 'BusController@get');
        });

        Route::group(['prefix' => 'locations'], function () {
            Route::post('/terminals', 'LocationController@terminals');
            Route::post('/provinces', 'LocationController@provinces');
        });

        Route::group(['prefix' => 'trips'], function () {
            Route::post('/', 'TicketController@store');
            Route::post('/get', 'TripController@getById');
            Route::post('/search/{type?}', 'TripController@searchApi');
        });
    });
});

Route::group(['prefix' => 'api'], function () {
    Route::group(['prefix' => 'trips'], function () {
        Route::post('/search', 'TripController@searchApi');
    });
    Route::group(['prefix' => 'locations'], function () {
        Route::post('/provinces', 'LocationController@provinces');
    });
    Route::group(['prefix' => 'liners'], function () {
        Route::post('/', 'LinerController@getById');
    });
    Route::group(['prefix' => 'tickets'], function () {
        Route::post('/', 'TicketController@reservations');
        Route::post('/session', 'TicketController@reserveSession');
    });
});

app/Customer.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;
use Laravel\Cashier\Billable;

class Customer extends Model{

    use Notifiable;
    use Billable;

    protected $fillable = [
        'first_name', 'last_name', 'mobile_number', 'email'
    ];


    public function getFullNameAttribute(){
        return $this->first_name. ' ' . $this->last_name;
    }

    public function getNameInitialsAttribute(){
        return $this->first_name[0].$this->last_name[0];
    }

    public function getPhoneNumberAttribute(){
        return '63'.substr($this->mobile_number, 1);
    }

}

app/Invoice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Invoice extends Model{

    const ACTIVE = 0;
    const REFUNDED = 1;

    protected $fillable = [
        'ticket_id', 'customer_id', 'amount', 'type', 'stripe_id', 'card_brand', 'card_last_four', 'paypal_email', 'transaction_id'
    ];

    protected $appends = [
        'invoice_no'
    ];

    public function customer(){
        return $this->belongsTo(Customer::class);
    }

    public function ticket(){
        return $this->belongsTo(Ticket::class);
    }

    public function getInvoiceNoAttribute() {
        return str_pad($this->id, 10, '0', STR_PAD_LEFT);
    }

}

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model{

    const PAID = 1;
    const PENDING = 0;
    const REFUNDED = 2;
    const CANCELLED = 3;

    protected $fillable = [
        'trip_id', 'customer_id', 'route_id', 'reserved_seats', 'amount', 'status'
    ];

    protected $appends = [
        'ticket_no'
    ];

    protected $casts = [
        'reserved_seats' => 'array'
    ];

    public function trip(){
        return $this->belongsTo(Trip::class);
    }

    public function customer(){
        return $this->belongsTo(Customer::class);
    }

    public function route(){
        return $this->belongsTo(Route::class);
    }

    public function invoice(){
        return $this->hasOne(Invoice::class);
    }

    public function passengers(){
        return $this->hasMany(Passenger::class);
    }

    public function getTicketNoAttribute() {
        return str_pad($this->id, 10, '0', STR_PAD_LEFT);
    }

    public function getTicketStatusAttribute(){
        if($this->status == self::PENDING){
            return 'Payment Pending';
        }elseif($this->status == self::REFUNDED){
            return 'Refunded';
        }else{
            return 'Paid';
        }
    }

}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Invoice;

use Stripe\Refund;
use Srmklive\PayPal\Services\ExpressCheckout;
use App\Ticket;
use App\Notifications\InvoiceRefund;

class InvoiceController extends Controller{

    public function index(Request $request){
        $invoices = Invoice::with('customer', 'ticket')->latest();

        $user = auth()->user();
        if(!$user->hasRole('admin')){
            $invoices = $invoices->whereHas('ticket', function($q) use($user){
                $q->whereHas('trip', function($q) use($user){
                    $q->whereHas('busNoScope', function($q) use($user){
                        $q->where('liner_id', $user->liner_id);
                    });
                });
            });
        }

        if(isset($request->q)){
            $invoices->where('id', (int)$request->q);
        }

        $invoices = $invoices->paginate(10);

        return view('admin.invoice.index', compact('invoices'));
    }

    public function view($id){
        $invoice = Invoice::with('customer', 'ticket')->where('id', $id)->firstOrFail();

        return view('admin.invoice.view', compact('invoice'));
    }

    public function issueRefund(Request $request){
        $invoice = Invoice::where('id', $request->id)->where('status', Invoice::ACTIVE)->first();

        if(!$invoice){
            flash('Invalid Invoice ID')->error();
            return redirect()->route('admin.invoice.index');
        }

        if($invoice->type == 1){
            $customer = $invoice->customer;
            try{
                $response = $customer->refund($invoice->transaction_id);
            }catch(Exception $e){
                flash('Unable to refund the invoice #'.$invoice->invoice_no.' please try again later');
                return redirect()->route('admin.invoice.view', $invoice->id);
            }

            if($response->status == 'succeeded'){
                $invoice->status = Invoice::REFUNDED;
                $invoice->ticket->status = Ticket::REFUNDED;
                $invoice->ticket->save();
                $customer->notify(new InvoiceRefund($invoice));
            }else{
                flash('Unable to refund the invoice #'.$invoice->invoice_no.' as this moment');
                return redirect()->route('admin.invoice.view', $invoice->id);
            }
            $invoice->save();
        }elseif($invoice->type == 2){
            $provider = new ExpressCheckout;
            $response = $provider->refundTransaction($invoice->transaction_id);

            if($response['ACK'] == 'Success'){
                $invoice->status = Invoice::REFUNDED;
                $invoice->ticket->status = Ticket::REFUNDED;
                $invoice->ticket->save();
                $invoice->customer->notify(new InvoiceRefund($invoice));
            }else{
                flash('Unable to refund the invoice #'.$invoice->invoice_no.' as this moment');
                return redirect()->route('admin.invoice.view', $invoice->id);
            }
            $invoice->save();
        }else{
            $invoice->status = Invoice::REFUNDED;
            $invoice->ticket->status = Ticket::REFUNDED;
            $invoice->ticket->save();
            $invoice->save();
        }
        flash('Successfully refunded the invoice #'.$invoice->invoice_no);
        return redirect()->route('admin.invoice.view', $invoice->id);
    }

}

resources/views/admin/invoice/index.blade.php
@extends('admin.layouts.admin')

@section('content')
<div class="card">
    <div class="card-body">
        <form>
            <div class="form-group mb-0">
                <div class="input-group">
                    <input type="text" class="form-control" name="q" placeholder="Search for invoice id">
                    <span class="input-group-append">
                        <button class="btn btn-primary" type="submit">Go!</button>
                    </span>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="card">
    @include('flash::message')
    <div class="table-responsive">
        <table class="table table-hover table-outline table-vcenter text-nowrap card-table">
            <thead>
                <tr>
                    <th class="text-center w-1"><i class="icon-people"></i></th>
                    <th>Customer</th>
                    <th>Invoice</th>
                    <th>Amount</th>
                    <th class="text-center">Payment Method</th>
                    <th class="text-center"><i class="fe fe-settings"></i></th>
                </tr>
            </thead>
            <tbody>
                @foreach($invoices as $invoice)
                <tr>
                    <td class="text-center">
                        <span class="avatar">{{ $invoice->customer->name_initials }}</span>
                    </td>
                    <td>
                        <div>{{ $invoice->customer->full_name }}</div>
                        <div class="small text-muted">
                            Created at: {{ $invoice->customer->created_at->format('M d, Y') }}
                        </div>
                    </td>
                    <td>
                        <div class="small text-muted">Invoice Number</div>
                        <div>{{ $invoice->invoice_no }}</div>
                    </td>
                    <td>
                        <div class="small text-muted">{{ count($invoice->ticket->reserved_seats) }} reserved ticket</div>
                        <div>PHP {{ number_format($invoice->amount, 2) }}</div>
                    </td>
                    <td class="text-center">
                        @if($invoice->type == 1)
                            <i class="payment payment-{{ strtolower($invoice->card_brand) }}"></i>
                        @elseif($invoice->type == 2)
                            <i class="payment payment-paypal"></i>
                        @else
                            Cash
                        @endif
                    </td>
                    <td class="text-center">
                        <a href="{{ route('admin.invoice.view', $invoice->id) }}" class="btn btn-secondary btn-sm">View</a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
{{ $invoices->render()}}
@endsection

resources/views/admin/invoice/view.blade.php
@extends('admin.layouts.admin')

@section('content')
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Invoice #{{ $invoice->invoice_no }}</h3>
        @if($invoice->status != 1)
        <div class="card-options">
            <form action="{{ route('admin.invoice.refund') }}" method="POST">
                @csrf
                <input type="hidden" name="id" value="{{ $invoice->id }}">
                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to issue a refund?')">Issue Refund</button>
            </form>
        </div>
        @endif
    </div>
    @include('flash::message')
    <div class="card-body">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <table class="table">
                    <thead>
                        <tr>
                            <th colspan="2" class="text-center">Invoice Information</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td scope="row">Payment Method</td>
                            <td>
                                @if($invoice->type == 1)
                                    <i class="payment payment-{{ strtolower($invoice->card_brand) }}"></i> ~ {{ $invoice->card_last_four }}
                                @elseif($invoice->type == 2)
                                    <i class="payment payment-paypal"></i> ~ {{ $invoice->paypal_email }}
                                @else
                                    Cash
                                @endif
                            </td>
                        </tr>
                        <tr>
                            <td scope="row">Transaction ID</td>
                            <td>
                                {{ $invoice->transaction_id }}
                            </td>
                        </tr>
                        <tr>
                            <td scope="row">Amount</td>
                            <td>
                                {{ number_format($invoice->amount, 2) }}
                            </td>
                        </tr>
                        @if($invoice->status == 1)
                        <tr>
                            <td scope="row">Status</td>
                            <td class="text-danger">
                                <b>REFUNDED</b>
                            </td>
                        </tr>
                        @endif
                    </tbody>
                </table>
                <table class="table">
                    <thead>
                        <tr>
                            <th colspan="2" class="text-center">Customer Information</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td scope="row">Full Name</td>
                            <td>
                                {{ $invoice->customer->full_name }}
                            </td>
                        </tr>
                        <tr>
                            <td scope="row">Email</td>
                            <td>
                                {{ $invoice->customer->email }}
                            </td>
                        </tr>
                        <tr>
                            <td scope="row">Mobile Number</td>
                            <td>
                                {{ $invoice->customer->mobile_number }}
                            </td>
                        </tr>
                    </tbody>
                </table>
                <table class="table">
                    <thead>
                        <tr>
                            <th colspan="2" class="text-center">Ticket Information</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                            $ticket = $invoice->ticket;
                            $trip = $ticket->trip;
                            $routes = $trip->routes->where('type', 0)->first();
                            $terminal = $routes->terminal;

                        @endphp
                        <tr>
                            <td scope="row" width="40%">Ticket Number</td>
                            <td>
                                {{ $ticket->ticket_no }}
                            </td>
                        </tr>

                        <tr>
                            <td scope="row" width="40%">Boarding Point</td>
                            <td>
                                {{ optional($terminal)->name ?? '-' }}
                            </td>
                        </tr>
                        <tr>
                            <td scope="row" width="40%">Dropping Point</td>
                            <td>
                                {{ optional($invoice->ticket->route)->terminal->name ?? '-' }}
                            </td>
                        </tr>
                        <tr>
                            <td scope="row">Reserved Seats</td>
                            <td>
                                {{ implode($invoice->ticket->reserved_seats, ',') }}
                            </td>
                        </tr>
                        <tr>
                            <td scope="row">Amount</td>
                            <td>
                                PHP {{ number_format($invoice->ticket->amount, 2) }}
                            </td>
                        </tr>
                        <tr>
                            <td scope="row">Status</td>
                            <td>
                                {{ $ticket->ticket_status }}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection